name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.12'

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint frontend
        run: npm run lint || true
        continue-on-error: true

      - name: Run frontend tests
        run: npm test --passWithNoTests || true
        continue-on-error: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          cd apps/api
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run Python tests
        run: |
          cd apps/api
          pytest tests/ --cov=. || true
        continue-on-error: true

  deploy-web:
    name: Deploy Web to Cloudflare Pages
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: |
          cd packages/rejection-tracker && npm run build
          cd ../notification-service && npm run build

      - name: Build Next.js app
        run: |
          cd apps/web
          npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.API_URL }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: brainsait-rcm
          directory: apps/web/out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Health check frontend
        run: |
          echo "Waiting for deployment (30s)..."
          sleep 30
          curl -f "https://brainsait-rcm.pages.dev" || echo "Health check skipped"
        continue-on-error: true

  deploy-api:
    name: Deploy API to Cloudflare Workers
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd apps/api
          pip install -r requirements.txt

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          NPHIES_API_KEY: ${{ secrets.NPHIES_API_KEY }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: API health check
        run: |
          echo "Waiting for API deployment (20s)..."
          sleep 20
          curl -f "https://api.brainsait-rcm.workers.dev/health" || echo "Health check skipped"
        continue-on-error: true

  smoke-tests:
    name: Post-Deployment Smoke Tests
    runs-on: ubuntu-latest
    needs: [deploy-web, deploy-api]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Test frontend homepage
        run: |
          curl -f "https://brainsait-rcm.pages.dev" -o /dev/null -s -w "%{http_code}\n" | grep -q "200"
        continue-on-error: true

      - name: Test demo page
        run: |
          curl -f "https://brainsait-rcm.pages.dev/demo" -o /dev/null -s -w "%{http_code}\n" | grep -q "200"
        continue-on-error: true

      - name: Test API health endpoint
        run: |
          curl -f "https://api.brainsait-rcm.workers.dev/health"
        continue-on-error: true

      - name: Deployment summary
        run: |
          echo "✅ Deployment completed successfully!"
          echo "Frontend: https://brainsait-rcm.pages.dev"
          echo "API: https://api.brainsait-rcm.workers.dev"
          echo "Demo: https://brainsait-rcm.pages.dev/demo"